
server:
    port: 8080

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: ''
        driver-class-name: org.h2.Driver
    h2: 
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        import:
            - "application-qa.yml"
            - "application-prod.yml"
    profiles:
        active:
            - "prod"
build:
    version: "1.0"

accounts:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "Developer"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267